# Generated by Django 3.2.9 on 2021-11-23 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('distance', '0002_alter_distancelocation_source_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='distancelocation',
            name='destination_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_address', to='location.address'),
        ),
        migrations.AlterField(
            model_name='distancelocation',
            name='source_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_address', to='location.address'),
        ),
    ]
