# Generated by Django 3.2.9 on 2021-11-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('distance', '0003_auto_20211123_0735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DistanceLocation',
            new_name='Distance',
        ),
    ]
